authentication/urls.py
from django.urls import path
from .views import sign_in,signup,verify_otp,resend_otp,user_logout,forgot_password,reset_password,add_shipping_address,editProfile,profile,set_default_address,edit_shipping_address,delete_shipping_address


app_name="auth"

urlpatterns=[
    path ("signin/" ,sign_in,name="signin"),
    path ("register/",signup,name="signup"),
    path("verify/<int:user_id>/",verify_otp,name="verify_otp"),
    path ('resend-otp/<int:user_id>/',resend_otp,name="resend_otp"),
    path('logout/', user_logout, name='logout'),
    path('forgot-password/', forgot_password, name='forgot_password'),
    path('reset-password/<uidb64>/<token>/', reset_password, name='reset_password'),
    path ('add-shipping-address/',add_shipping_address,name="add_shipping_address"),
    path ("edit-shipping-address/<int:id>/",edit_shipping_address,name="edit_shipping_address"),
   path('address/<int:address_id>/delete/',delete_shipping_address, name='delete_shipping_address'),
       path('address/<int:address_id>/set-default/',set_default_address, name='set_default_address'),

    path ("profile/",profile,name="profile"),
    path ("edit_profile/",editProfile,name="edit_profile"),

]

cart/urls.py
from django.urls import path
from .views import get_cart,remove_from_cart,update_cart


app_name="cart"

urlpatterns=[
    path("all/",get_cart,name="cartproducts"),
     path('remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('update/<int:product_id>/', update_cart, name='update_cart'),
]

main/urls.py
from django.urls import path
from .views import index_view,Faq_view,about_view

app_name="main"

urlpatterns=[
    path("",view=index_view,name="index"),
    path("faq/",view=Faq_view,name="faq"),
    path("about/",view=about_view,name="about"),
]

shalom_enterprise/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("auth/",include("authentication.urls")),
    path("",include("main.urls")),
    path("products/",include("products.urls")),
    path("cart/",include("cart.urls")),
    path("checkout/",include("checkout.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser,ShippingAddress


GHANA_REGIONS = [
    ('', 'Select Region'),
    ('Ahafo', 'Ahafo'),
    ('Ashanti', 'Ashanti'),
    ('Bono', 'Bono'),
    ('Bono East', 'Bono East'),
    ('Central', 'Central'),
    ('Eastern', 'Eastern'),
    ('Greater Accra', 'Greater Accra'),
    ('North East', 'North East'),
    ('Northern', 'Northern'),
    ('Oti', 'Oti'),
    ('Savannah', 'Savannah'),
    ('Upper East', 'Upper East'),
    ('Upper West', 'Upper West'),
    ('Volta', 'Volta'),
    ('Western', 'Western'),
    ('Western North', 'Western North'),
]



class CustomUserCreationForm(UserCreationForm):
    confirm_password = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}),
        required=True,
    )

    class Meta:
        model = CustomUser
        fields = ['email', 'first_name', 'last_name', 'phone_number', 'password1', 'password2', 'confirm_password']
        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'}),
            'phone_number': forms.TextInput(attrs={'placeholder': 'Phone Number'}),
            'password1': forms.PasswordInput(attrs={'placeholder': 'Password'}),
            'password2': forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        confirm_password = cleaned_data.get('confirm_password')

        if password1 and confirm_password and password1 != confirm_password:
            raise forms.ValidationError("Passwords do not match.")

        return cleaned_data
    


# forms.py
from django import forms
from .models import ShippingAddress
class ShippingAddressForm(forms.ModelForm):
    region = forms.ChoiceField(choices=GHANA_REGIONS, widget=forms.Select(attrs={'class': 'form-control'}))
    
    class Meta:
        model = ShippingAddress
        fields = ['full_name', 'phone', 'address_line_1', 'address_line_2', 'city', 'region', 'is_default']
        widgets = {
            'is_default': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

authentication/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import CustomUserCreationForm
from .utils import create_otp_for_user,send_otp_email,generate_otp,send_forgot_password_email
from .models import CustomUser,OTP
from django.utils import timezone
from django.http import JsonResponse
from django.contrib.auth import authenticate, login,logout
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.urls import reverse
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from .forms import ShippingAddressForm
from .models import ShippingAddress
from django.contrib.auth.decorators import login_required
from products.models import Cart,Wishlist
from checkout.models import Order,OrderItem


from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.contrib import messages



def sign_in(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        # Authenticate the user
        user = authenticate(request, email=email, password=password)

        if user is not None:
       
            if user.is_verified:
               
                login(request, user)
                messages.success(request, "You have been logged in successfully!")
                return redirect('main:index')  
            else:
                messages.error(request, "Your account is not verified. Please verify your email.")
                return redirect('auth:verify_otp', user_id=user.id)  
        else:
           
            messages.error(request, "Invalid email or password.")
            return redirect( 'auth:signin')

  
    return render(request, 'authentication/signin.html')

def signup(request):
    if request.method == 'POST':
        # Extract data from POST
        first_name = request.POST.get('first_name', '').strip()
        last_name = request.POST.get('last_name', '').strip()
        email = request.POST.get('email', '').strip().lower()  # Normalize email
        password = request.POST.get('password', '')
        confirm_password = request.POST.get('confirm_password', '')
        phone_number = request.POST.get('phone_number', '').strip()

        # Basic validation
        if password != confirm_password:
            messages.error(request, "Passwords do not match.")
            return render(request, 'authentication/signup.html')
            
        if len(password) < 6:
            messages.error(request, "Password must be at least 6 characters long.")
            return render(request, 'authentication/signup.html')

        if not (any(c.isupper() for c in password) and any(c.isdigit() for c in password)):
            messages.error(request, "Password must contain at least one capital letter and one number.")
            return render(request, 'authentication/signup.html')

        # Check for existing email or phone number before creating user
        error_messages = []
        if CustomUser.objects.filter(email__iexact=email).exists():
            error_messages.append("This email is already registered. Please use a different email or log in.")
        
        if CustomUser.objects.filter(phone_number=phone_number).exists():
            error_messages.append("This phone number is already registered. Please use a different number or log in.")
        
        if error_messages:
            for msg in error_messages:
                messages.error(request, msg)
            return render(request, 'authentication/signup.html')

        try:
            user = CustomUser(
                first_name=first_name,
                last_name=last_name,
                email=email,
                phone_number=phone_number,
                is_verified=False
            )
            user.set_password(password)
            user.save()

            # Generate and send OTP
            create_otp_for_user(user)

            return redirect('auth:verify_otp', user_id=user.id)
            
        except Exception as e:
            # Log the actual error for debugging
            print(f"Error creating user: {str(e)}")
            # Show generic error message to user
            messages.error(request, "We encountered an issue creating your account. Please try again.")
            return render(request, 'authentication/signup.html')
            
    return render(request, 'authentication/signup.html')

def verify_otp(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)

    if request.method == 'POST':
        otp_entered = request.POST.get('otp')
        print(otp_entered)

        # Get the latest OTP for the user
        latest_otp = OTP.objects.filter(user=user).order_by('-created_at').first()
        print(latest_otp.otp_code)

        if latest_otp and not latest_otp.is_expired() and latest_otp.otp_code == otp_entered:
            user.is_verified = True  # Mark user as verified
            user.save()
            messages.success(request, "Email verified successfully! You can now log in.")
            return redirect('auth:signin')
        else:
            messages.error(request, "Invalid or expired OTP. Please try again.")
            return redirect('auth:verify_otp', user_id=user.id)  # Redirect back to the same page

    return render(request, 'authentication/OTPverification.html', {'user_id': user.id})


def resend_otp(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)
    
    # Generate a new OTP
    otp_code = generate_otp()
    
    expires_at = timezone.now() + timezone.timedelta(minutes=5)
    
    # Create a new OTP instance
    OTP.objects.create(
        user=user,
        otp_code=otp_code,
        expires_at=expires_at
    )
    
    send_otp_email(user.email, otp_code)
    
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return JsonResponse({
            'status': 'success',
            'message': 'A new OTP has been sent to your email.',
        })
    
    # Handle non-AJAX requests
    messages.success(request, "A new OTP has been sent to your email.")
    return redirect('auth:verify_otp', user_id=user.id)





def user_logout(request):
    logout(request)  # Log out the user
    return redirect('auth:signin')  # Redirect to the sign-in page






class CustomPasswordResetTokenGenerator(PasswordResetTokenGenerator):
    def _make_hash_value(self, user, timestamp):
        return f"{user.pk}{timestamp}{user.is_verified}"

password_reset_token_generator = CustomPasswordResetTokenGenerator()

def forgot_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = CustomUser.objects.filter(email=email).first()

        if user:
            # Generate a password reset token
            token = password_reset_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))

            # Create the reset link
            reset_link = request.build_absolute_uri(
                reverse('auth:reset_password', kwargs={'uidb64': uid, 'token': token})
            )

            # Send the email
            message = render_to_string('authentication/password_reset_email.html', {
                'user': user,
                'reset_link': reset_link,
            })
            
            send_forgot_password_email(message=message,user=user)

            messages.success(request, "A password reset link has been sent to your email.")
            return redirect('auth:signin')
        else:
            messages.error(request, "No user found with this email address.")
            return redirect('auth:forgot_password')

    return render(request, 'authentication/forgot_password.html')





def reset_password(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None

    if user and password_reset_token_generator.check_token(user, token):
        if request.method == 'POST':
            new_password = request.POST.get('new_password')
            confirm_password = request.POST.get('confirm_password')

            if new_password == confirm_password:
                user.set_password(new_password)
                user.save()
                messages.success(request, "Your password has been reset successfully. You can now log in.")
                return redirect('auth:signin')
            else:
                messages.error(request, "Passwords do not match.")
                return redirect('auth:reset_password', uidb64=uidb64, token=token)  # Fixed here

        return render(request, 'authentication/reset_password.html')
    else:
        messages.error(request, "Invalid or expired password reset link.")
        return redirect('auth:signin')








def editProfile(request):

    
    user = request.user  

    if request.method == "POST":
        try:
            first_name = request.POST.get('first_name', '').strip()
            last_name = request.POST.get('last_name', '').strip()
            email = request.POST.get('email', '').strip()
            phone_number = request.POST.get('phone_number', '').strip()

            # Basic validation
            if not first_name:
                raise ValidationError("First name is required.")
            if not last_name:
                raise ValidationError("Last name is required.")
            if not email:
                raise ValidationError("Email is required.")
            
            # Email format validation
            if '@' not in email:

authentication/templates/authentication/password_reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Hello {{ user.first_name }},</p>
<p>You requested a password reset. Click the link below to reset your password:</p>
<p><a href="{{ reset_link }}">Reset Password</a></p>
<p>If you did not request this, please ignore this email.</p>
</body>
</html>

authentication/templates/authentication/signin.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>
            SA Express | Sign in
        </title>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css'  %}"/>

		<!-- Slick -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css'  %}"/>
		<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css'  %}"/>

		<!-- nouislider -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css '  %}"/>

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css'  %}">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

        <style>
            .input-group {
                position: relative;
                width: 100%;
            }
            .input-icon {
                position: absolute;
                left: 10px;
                top: 10px;
                color: #999;
                z-index: 10;
            }
            .password-toggle {
                position: absolute;
                right: 10px;
                top: 10px;
                color: #999;
                cursor: pointer;
                z-index: 10;
            }
            .has-icon {
                padding-left: 40px;
            }
        </style>
    </head>
	<body>
		<!-- HEADER -->
		<header>
			<!-- TOP HEADER -->
			<div id="top-header">
				<div class="container">
					<ul class="header-links pull-left">
						<li><a href="#"><i class="fa fa-phone"></i> +233552180200</a></li>
						<li><a href="#"><i class="fa fa-envelope-o"></i> email@email.com</a></li>
						<li><a href="#"><i class="fa fa-map-marker"></i> 1734 Ghana Road</a></li>
					</ul>
					<ul class="header-links pull-right">
						<li><a href="#"><i class="fa fa-dollar"></i> GHS</a></li>
						<li><a><i class="fa fa-user-plus"></i> Register</a></li>
					</ul>
				</div>
			</div>
			<!-- /TOP HEADER -->

			<!-- MAIN HEADER -->
			<div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-3">
							<div class="header-logo">
								<a href="{% url 'main:index'%}" class="logo">
									<h2 style="color: white;">
										<span style="color: #D10024;">
											SA 
										</span>
										
										Express</h2>
								</a>
							</div>
						</div>
						<!-- /LOGO -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
			<!-- /MAIN HEADER -->
		</header>
		<!-- /HEADER -->
		
		<!-- SECTION -->
		
    <!-- SECTION -->
    <div class="section" style="margin-top:20px;margin-bottom: 20px;">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <!-- Display messages -->
                    {% if messages %}
                        <div class="messages">
                            {% for message in messages %}
                                <div class="alert {% if message.tags == 'success' %}alert-green{% elif message.tags == 'error' %}alert-red{% endif %}" role="alert">
                                    {{ message }}
                                    <button type="button" class="close-btn" aria-label="Close">
                                        <span class="sr-only">Close</span>
                                        <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                                        </svg>
                                    </button>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}

                    <div class="billing-details">
                        <div class="section-title text-center">
                            <h3 class="title">Sign In</h3>
                        </div>

                        <!-- Sign-in form -->
                        <form method="post" action="{% url 'auth:signin' %}">
                            {% csrf_token %}
                            
                            <!-- Email field -->
                            <div class="form-group">
                                <div class="input-group">
                                    <i class="fa fa-envelope input-icon"></i>
                                    <input class="input has-icon" type="email" name="email" placeholder="Email" required>
                                </div>
                            </div>
                            
                            <!-- Password field -->
                            <div class="form-group">
                                <div class="input-group">
                                    <i class="fa fa-lock input-icon"></i>
                                    <input class="input has-icon" type="password" name="password" id="password" placeholder="Password" required>
                                    <i class="fa fa-eye password-toggle" id="togglePassword"></i>
                                </div>
                            </div>

                            <!-- Forgot password link -->
                            <div class="text-right text-danger">
                                <p><a href="{% url 'auth:forgot_password'%}">Forgot your password?</a></p>
                            </div>
                            
                            <!-- Submit button -->
                            <div class="form-group text-center">
                                <button type="submit" class="primary-btn">Sign In</button>
                            </div>
                            
                            <!-- Register link -->
                            <div style="display: flex; align-items: center; justify-content: center; gap: 10px;">
                                <hr style="flex-grow: 1; border: none; border-top: 1px solid #ccc; height: 1px;">
                                <p style="margin: 0;">Don't have an account? <a href="{% url 'auth:signup' %}">Register here</a></p>
                                <hr style="flex-grow: 1; border: none; border-top: 1px solid #ccc; height: 1px;">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
   

		<!-- /SECTION -->

		<!-- FOOTER -->
		<footer id="footer">
			<!-- top footer -->
			<div class="section">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">About Us</h3>
								<p>SA Express</p>
								<ul class="footer-links">
									<li><a href="#"><i class="fa fa-map-marker"></i>1734 Ghana Road</a></li>
									<li><a href="#"><i class="fa fa-phone"></i>+233552180200</a></li>
									<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Categories</h3>
								<ul class="footer-links">
									<li><a href="#">Hot deals</a></li>
									<li><a href="#">Laptops</a></li>
									<li><a href="#">Smartphones</a></li>
									<li><a href="#">Cameras</a></li>
									<li><a href="#">Accessories</a></li>
								</ul>
							</div>
						</div>

						<div class="clearfix visible-xs"></div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Information</h3>
								<ul class="footer-links">
									<li><a href="#">About Us</a></li>
									<li><a href="#">Contact Us</a></li>
									<li><a href="#">Privacy Policy</a></li>
									<li><a href="#">Terms & Conditions</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Service</h3>
								<ul class="footer-links">
								
									
									<li><a href="#">Help</a></li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /top footer -->

			<!-- bottom footer -->
			<div id="bottom-footer" class="section">
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-12 text-center">
							<ul class="footer-payments">
								<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
								<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
							</ul>
							<span class="copyright">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | SA Express
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</span>
						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /bottom footer -->
		</footer>
		<!-- /FOOTER -->

		<!-- jQuery Plugins -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/slick.min.js' %}"></script>
		<script src="{% static 'js/nouislider.min.js' %}"></script>
		<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>

        <script>
            $(document).ready(function() {

				document.querySelectorAll('.messages .close-btn').forEach(function(button) {
        button.addEventListener('click', function() {
            const alert = this.closest('.alert');
            if (alert) {
                alert.remove();
            }
        });
    });

	
                // Password visibility toggle
                $('#togglePassword').click(function() {
                    const passwordField = $('#password');
                    const passwordFieldType = passwordField.attr('type');
                    
                    // Toggle password visibility
                    if (passwordFieldType === 'password') {
                        passwordField.attr('type', 'text');
                        $(this).removeClass('fa-eye').addClass('fa-eye-slash');
                    } else {
                        passwordField.attr('type', 'password');
                        $(this).removeClass('fa-eye-slash').addClass('fa-eye');
                    }
                });
            });
        </script>
	</body>
</html>